- name: Debian Patch installtion 
  block: 
      - name: Patching Debian based systems 
        apt:
           update_cache: yes
           cache_valid_time: 3600
           upgrade: dist 
        when: ansible_facts.os_family == "Debian"

      - name: Patching security for the bedian os 
        apt:
           name: "*"
           state: latest
           security: true

      - name: Debug skipped tasks
        debug: 
              var: ansible_skip_tags

  rescue:
      - name: Handle failure in Debian patch installation
        debug:
             msg: "Debian patch installation failed."