- name: Reboot the system
  block:

      - name: Reboot the server
        ansible.builtin.reboot:
           reboot_timeout: 360
        ignore_errors: true
        when: reboot

  rescue: 
     
      - name: Handle failure in reboot
        debug: 
           msg: An error occured while rebooting the system 
