- name: RedHat system patch installation
  block:
      - name: Install patches in RedHat systems
        yum:
           name: '*'
           state: latest
           security: yes
           exclude: "{{ exclude_packages }}"
        when: ansible_facts.os_family == "RedHat"

      - name: Debug skipped tasks
        debug:
             var: ansible_skip_tags
  
  rescue: 
      - name: Handle failure in RedHat patch installation 
        debug: 
            msg: "RedHat patch installation failed."