- name: Restart the stopped services 
  block: 
      - name: Restart the stopped services 
        service:
          name: "{{ item }}"
          state: started
        loop: "{{ items }}"
        register: service_status 

      # - name: Svae the service status 
      #   copy: 
      #     content: "{{ service_status.stdout | default('No stdout captured or applicable') }}"  
      #     dest: "{{ Patching_dir }}/{{ stage_dir2 }}/restart_services.txt"

  rescue:
      - name: Handle failure in stopping the services 
        debug:
            msg: Unable to stopped the services {{ items }}