- name: Playbook for system patching automate
  hosts: localhost
  gather_facts: yes
  become: no
  # roles:
  #   - Pre-Patching
  #   - Patching
  #   - Post-Patching
  vars:
    Pre_Patching: "/home/tanisha/Ansible_Patching_Playbook"
    timestamp: "{{ ansible_date_time.iso8601_basic_short }}"
  tasks: 
       - name: Create a temporary directory
         file: 
           path: "{{ Pre_Patching }}/Pre_Patching"
           state: directory
           mode: '0755'

       - name: Create the zip of the folder 
         community.general.archive:
           path: "{{ Pre_Patching }}/Pre_Patching" 
           dest: "{{ Pre_Patching }}/Pre_Patching{{ timestamp }}.zip"
           format: zip

       - name: Confirm the zip creation 
         debug:
            msg: "Evidence zip created at {{ Pre_Patching }}/Pre_Patching{{ timestamp }}.zip."
