---

- name: Resource Health Check Post Patching 
  block:
    - name: Create a temporary directory
      file: 
        path: "{{ Patching_stage }}/{{stage_dir}}"
        state: directory
        mode: '0755' 

    - name: Resource Health Check  
      include_role:
        name: Pre-Patching
        tasks_from: Verify_resources.yml 
      vars: 
        stage_dir: "{{ stage_dir1 }}"
        Pre_Patching: "{{ Patching_stage }}"
  rescue:
    - name: Resource Health Check Failure 
      debug:
          msg: "An error occured- Resource Health Check Post Patching failed."