- name: Mail notifiaction
  block:

     - name: Mail notification 
       community.general.mail:
            subject: System {{ ansible_hostname }} has been successfully provisioned.
            delegate_to: localhost
       when: notifiaction
       
  rescue:
      - name: Handle failure for notification
        debug:
           msg: Unable to send notification 