- name: Post Patch Service Revalidation 
  block:
    - name: Service Revalidation Check
      include_role:
        name: Pre-Patching
        tasks_from: Gather_Active_Services.yml
      vars:
        stage_dir: "{{ stage_dir2 }}"
        Pre_Patching: "{{ Patching_stage }}"

  rescue:

    - name: Fail Service Revalidation
      fail:
        msg: Service Revalidation Failed at post-patch