Patching_dir: "/home/tanisha/Ansible_Patching_Playbook"
timestamp: "{{ lookup('pipe', 'date -d \"minutes\" +\"%Y%m%d %r\"') }}"
stage_dir1: "Patching"
items: 
  - apache2
  - nginx
  - mysql
reboot: false
reboot_timeout: 360