- name: Gather running services
  block:
       - name: Running services
         shell: systemctl list-units --type=service --state=running >> {{ Pre_Patching }}/{{stage_dir}}/running_services.txt

       - name: Confirm the running services info 
         debug:
             msg: "Running services stored in  {{ Pre_Patching }}/{{stage_dir}}/running_services.txt."
  rescue:
        
        - name: Handle failure in gathering running services 
          debug: 
              msg: "Unable to gather running services information."