- name: Gather evidence before patching 
  block:
     - name: Create the zip of the folder 
       community.general.archive:
          path: "{{ Pre_Patching }}/{{stage_dir}}" 
          dest: "{{ Pre_Patching }}/{{stage_dir}}{{ timestamp }}.zip"
          format: zip

     - name: Confirm the zip creation 
       debug:
          msg: "Evidence zip created at {{ Pre_Patching }}/{{stage_dir}}{{ timestamp }}.zip."

  rescue:
      
       - name: Handle failure in gathering evidence 
         fail:
             msg: "Unable to zip the evidence folder."